project_id: 393649
api_key: 0a8dbf661866aa2f91f42fdaa43dc657
api_token: 501e3b18df31a6e872ad39ad2a46d1e68be1722bd8f06e6d01e95e2c2040ea18c5292c67361dfdbb
base_path: i18n
preserve_hierarchy: true
files:
  - source: template.pot
    translation: '%locale_with_underscore%.po'
    translation_replace:
      en_US: en
      cs_CZ: cs
      es_ES: es
      pl_PL: pl
      hu_HU: hu
